name: mca-windows
on:
  push:
    paths:
      - 'mca/windows/**'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat mca/standard/main.cpp
      - run: cat mca/windows/main.cpp
